# Generated by Django 2.2 on 2021-05-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=45)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_name', models.CharField(max_length=70)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('tequila', 'Tequila'), ('gin', 'Gin'), ('whiskey', 'Whiskey'), ('vodka', 'Vodka'), ('rum', 'Rum'), ('bourbon', 'Bourbon'), ('cognac', 'Cognac'), ('wine', 'Wine'), ('champagne', 'Champagne'), ('beer', 'Beer')], default='tequila', max_length=6)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('instruction', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='mainApp.User')),
            ],
        ),
    ]
